variables:
  2t:
    var: 2t
    long: 2 meter temperature
    wg_unit: {CERRA:   K,
               MEPS:    K,
               NORA3:   K,
               ERA5:    K,
               DEFAULT: K}
    verif_unit: K
    obs_name: air_temperature
    obs_units: K
    level_type: sfc

  sp:
    var: sp
    long: Surface pressure
    wg_unit: {CERRA:   Pa,
               MEPS:    Pa,
               NORA3:   Pa,
               ERA5:    Pa,
               DEFAULT: Pa}
    verif_unit: Pa
    obs_name: surface_air_pressure
    obs_units: Pa
    level_type: sfc

  tp:
    var: tp
    long: Total precipitation amount
    wg_unit:  {CERRA:   kg/m^2,
               MEPS:    kg/m^2,
               NORA3:   kg/m^2,
               ERA5:    m,
               DEFAULT: kg/m^2}
    verif_unit: kg/m^2
    obs_name: precipitation_amount_1h
    obs_units: kg/m^2
    level_type: sfc


  mlsp:
    var: msl
    long: Mean sea level pressure
    wg_unit:  {CERRA:   Pa,
               MEPS:    Pa,
               NORA3:   Pa,
               ERA5:    Pa,
               DEFAULT: Pa}
    verif_unit: Pa
    obs_name: surface_air_pressure #check with Rolf
    obs_units: kg/m^2
    level_type: sfc


  wind:
    var: 10si # derived channel
    long: wind speed
    wg_unit:  {CERRA:   m/s,
               MEPS:    m/s,
               NORA3:   m/s,
               ERA5:    m/s,
               DEFAULT: m/s}
    verif_unit: m/s
    obs_name: wind_speed
    obs_units: m/s
    level_type: sfc


coordinates:
    sfc:
        valid_time: valid_time
        lat: latitude
        lon: longitude
        stream: stream
        forecast_step: leadtime
        forecast_reference_time: forecast_reference_time
        ncells: ncells
    #pl:
      #not needed

dimensions:
    valid_time:
      wg: valid_time
      verif: time
    lat: 
      wg: latitude
      verif: latitude
      verif_unit: degrees_north
    lon: 
      wg: longitude
      verif: longitude
      verif_unit: degrees_east
    pressure_level:
      wg: pressure
      verif: pressure
      verif_unit: hPa
    forecast_reference_time: 
      wg: forecast_reference_time
      verif: forecast_reference_time
    forecast_step:
      wg: leadtime
      verif: forecast_period
      long: time since forecast_reference_time
      verif_unit: hours
    stream:
      wg: stream
      verif: stream
    ncells:
      wg: ncells
      verif: ncells