### NEED TO RUN THIS PARTICULAR RUN ID FROM MULTI EXPERIMENTS?

#global_plotting_options:
#  regions: ["europe", "global"] # Have regions here, if you want for them to apply to all streams (map generation)
#  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
#  animation_format: "gif" #options: "mp4", "gif"
#  dpi_val : 300
#  fps: 2
#  n_bins: 50 #number of bins for histograms. 
#  log_x: true #use log scale for x axis in histograms. 
#  log_y: true #use log scale for y axis in histograms. 
#  ERA5:
#    use_datashader: false
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    add_healpix_grid: false
#    healpix_nside: 4
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40


# max_workers: 36  # hard cap on parallel workers (I/O, plotting, scoring)

evaluation:
  metrics  : ["rmse"]
  # regions: ["global", "nhem"] # Have regions here, if you want for them to apply to all streams (scores calculation)
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation 
  plot_score_timeseries: false #plot timeseries of scores across forecast steps. 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: false
  num_processes: 0  #options: int, "auto", 0 means no parallelism (default)
  #baseline: "e5yd4ew1"
  #max_plot_lead_time_hours: 120


default_streams:
  SurfaceCombined:
    regions: ["global"]
    channels: ["obsvalue_tsts_0", "obsvalue_t2m_0", "obsvalue_td2m_0", "obsvalue_u10m_0", "obsvalue_v10m_0", "obsvalue_pmsl_0", "obsvalue_ps_0"]
    # channels : ["10u", "10v", "2t", "q_850", "t_850", "u_850", "v_850", "z_500"]
    evaluation:
      forecast_step: "all"
      sample: "1-15"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: [1, 2]
      forecast_step: "all" #supported: "all", [1,2,3,...], "1-50" (equivalent of [1,2,3,...50])
      ensemble: "all" #supported: "all", "mean", [0,1,2]
      plot_maps: true
      plot_bias: true
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :

  us8i5kxm:
    label: "Seb JEPA space masking, ERA5 input, forecasting, unfreeze, correct nominal time mapping, 1h ERA5 output"
    results_base_dir : "./results/us8i5kxm/"
    comparison_lead_time_offset_hours: 5