#optional: if commented out all is taken care of by the default settings
# NB. global options apply to all run_ids 

global_plotting_options:
 regions: ["global"] # Have regions here, if you want for them to apply to all streams (map generation)
 image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
 animation_format: "mp4" #options: "mp4", "gif"
 # log_colorbar: true

#  dpi_val : 300
#  fps: 2
#  n_bins: 50 #number of bins for histograms. 
#  log_x: true #use log scale for x axis in histograms. 
#  log_y: true #use log scale for y axis in histograms. 
#  ERA5:
#    use_datashader: false
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    add_healpix_grid: false
#    healpix_nside: 4
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40


# Long rollout ZipStore archives are large enough that process-parallel I/O exhausts host memory.
max_workers: 1

evaluation:
  metrics  : ["rmse", "mae"]
  # regions: ["global", "nhem"] # Have regions here, if you want for them to apply to all streams (scores calculation)
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation
  plot_score_animations: false #plot animations of score maps across forecast steps. it slows down score computation
  plot_score_timeseries: false #plot timeseries of scores across forecast steps. 
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: false
  # baseline: "ar40mckx"


default_streams:
  ERA5:
    #offset: "1h" #optional: specify a timedelta offset to infer init_time when source_interval is missing. Format examples: "1h", "30m", "2h30m".
    regions: ["global"]
    channels: ["2t", "10ff", "10u", "10v", "z_500", "t_850", "u_850", "v_850", "q_850", ]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: "all"
      forecast_step: "all" #supported: "all", [1,2,3,...], "1-50" (equivalent of [1,2,3,...50])
      ensemble: "all" #supported: "all", "mean", [0,1,2]
      plot_maps: true
      plot_bias: false
      plot_target: true
      plot_histograms: true
      plot_animations: true
      
run_ids :
  # z746swf3:
  #   label: "pretrained model z746swf3"
  #   results_base_dir : "./results/z746swf3/"

  # fsz30v4j:
  #   label: "10 day rollout with claude hacks, based off fx276yn3"
  #   results_base_dir : "./results/fsz30v4j/"

  rasqhob6:
    label: "10 day rollout with our code, based off igsqdagc"
    results_base_dir : "./results/rasqhob6/"
    
 