name: Task / Issue
description: A task or issue that should take less than a week to complete.
title: "[ISSUE] "

body:
  - type: markdown
    attributes:
      value: |
        Describe the task. It can be a feature, documentation, etc.
        
        Be specific and provide context.

  - type: input
    id: hedgedoc_url
    attributes:
      label: Hedgedoc URL, if you are keeping notes, plots, logs in hedgedoc.
      description: Paste a link to logs, screenshots, or related resources
      placeholder: "https://gitlab.jsc.fz-juelich.de/hedgedoc/..."
    validations:
      required: false

  - type: checkboxes
    id: area
    attributes:
      label: Area
      description: The general area this task relates to.
      options:
        - label: datasets, data readers, data preparation and transfer
        - label: model
        - label: infrastructure and engineering
        - label: evaluation, export and visualization
        - label: documentation
    validations:
      required: true



