# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

day_of_year_conditioning:
  type: time_conditioning
  conditioning: True
  filenames: null
  timestep_conditioning: scalar
  conditioning_type: time_based
  value_type: day
  embed:
    net: linear
    dim_embed: 256
  conditioning_FE:
    type: add
    dim_embed: 256
