# Conventional observation input-only stream for forecast fine-tuning.
SurfaceCombined:
  type: obs
  stream_id: 2
  filenames: ['observations-ea-ofb-0001-1979-2025-combined-surface-v5.zarr']
  geoinfos: ['reportype', 'stalt', 'lsm']
  token_size: 512
  tokenize_spacetime: false
  max_num_targets: -1
  forcing: true
  embed: {net: transformer, num_tokens: 1, num_heads: 2, dim_embed: 256, num_blocks: 2}
  embed_target_coords: {net: linear, dim_embed: 256}
  target_readout: {num_layers: 2, num_heads: 4}
  pred_head: {ens_size: 1, num_layers: 1}