import logging
import re
from dataclasses import dataclass
from pathlib import Path

import prefect.runtime.flow_run
import prefect.runtime.task_run
from prefect.artifacts import acreate_markdown_artifact

from weathergen.prefect_dags.cmd_runners import (
    CmdContext,
    Command,
    get_command_runner,
    run_cmd,
)
from weathergen.prefect_dags.prefect_logging import get_run_logger
from weathergen.prefect_dags.prefect_wrapper import task
from weathergen.prefect_dags.result import OpError, Result, is_err
from weathergen.prefect_dags.run import get_head_tail_logs
from weathergen.prefect_dags.sbatch import (
    SlurmJobResult,
    _artifact_key_part,
    _format_output_section,
    wait_completion_single,
)
from weathergen.prefect_dags.slurm import SlurmJobId, SlurmSubmissionResult

_logger = logging.getLogger(__name__)


@dataclass
class LaunchSlurm:
    """
    All the tracking information when using the launch-slurm
    command.
    """

    # The run_id generated by the weathergenerator launch-slurm command.
    wg_run_id: str

    # The name of the stage (e.g. "train")
    stage: str

    # The main jobs:
    # The stdout stderr paths are reconstructed from wg_work_dir:
    # They should be "{wg_work_dir}/WeatherGenerator/logs/{wg_run_id}/weathergen.part{n+1}.{job_id}.out/err"
    slurm_jobs: list[SlurmSubmissionResult]
    # Cleanup job: TODO, it is hard to get from summary right now
    # cleanup_slurm_job: SlurmSubmissionResult | None
    # A path to the working dir in weathergenerator (called slurm_... typically)
    wg_work_dir: str


# Matches the per-stage summary lines printed by launch_slurm.py, e.g.:
#   [train     ] 'train' | run_id=c9ika5od | job_ids=[921904] |
#       start_after=immediately | dir=/iopsstor/.../slurm_weathergen_c9ika5od_dir
_SUMMARY_LINE_RE = re.compile(
    r"run_id=(?P<run_id>\S+)\s*\|"
    r"\s*job_ids=\[(?P<job_ids>[^\]]*)\]\s*\|"
    r".*?dir=(?P<dir>\S+)"
)


# Truncation limits for command output embedded in markdown artifacts, per
# side (head/tail). Same values as get_head_tail_logs in run.py.
_MAX_OUTPUT_BYTES = 100_000
_MAX_OUTPUT_LINES = 100


def _head_tail(text: str) -> str:
    """Truncate `text` to its head and tail (by lines and bytes) for artifacts.

    Returns the text unchanged when it fits within a single head window;
    otherwise returns head + elision marker + tail.
    """

    def _clip(s: str) -> str:
        return s.encode()[:_MAX_OUTPUT_BYTES].decode(errors="ignore")

    lines = text.splitlines()
    if len(lines) <= _MAX_OUTPUT_LINES and len(text.encode()) <= _MAX_OUTPUT_BYTES:
        return text
    head = _clip("\n".join(lines[:_MAX_OUTPUT_LINES]))
    tail = _clip("\n".join(lines[-_MAX_OUTPUT_LINES:]))
    return f"{head}\n[... truncated ...]\n{tail}"


def _output_md_section(title: str, body: str | None) -> str:
    """A markdown section with head/tail-truncated command output.

    Uses 4-backtick fences so content containing ``` doesn't break the block.
    """
    if body is None:
        return f"### {title}\n\n_(not available)_\n\n"
    if body == "":
        return f"### {title}\n\n_(empty)_\n\n"
    return f"### {title}\n\n````\n{_head_tail(body)}\n````\n\n"


async def _publish_launch_error_artifact(
    logger: logging.Logger,
    stage: str,
    from_run_id: str | None,
    error: str,
    stdout: str | None,
    stderr: str | None,
) -> None:
    """Publish a markdown artifact for a failed launch-slurm.py invocation.

    On failure there is no wg run_id to key the artifact on (the key of the
    success artifact relies on parsing the output, which is exactly what
    failed), so key on the task run id instead: it is unique per attempt,
    so retries do not supersede each other's diagnostics.

    Best effort: a failure to publish must not mask the original error.
    """
    short = (prefect.runtime.task_run.id or prefect.runtime.flow_run.id or "")[:8] or "local"
    key = f"wg-launch-error-{_artifact_key_part(stage)}-{_artifact_key_part(short)}"
    md = (
        f"## WeatherGenerator launch-slurm FAILED\n\n"
        f"- **Stage:** `{stage}`\n"
        f"- **From run ID:** `{from_run_id}`\n"
        f"- **Error:** {error}\n\n"
        + _output_md_section("launch-slurm.py stdout", stdout)
        + _output_md_section("launch-slurm.py stderr", stderr)
    )
    try:
        await acreate_markdown_artifact(
            key=key,
            markdown=md,
            description=f"wg launch failure, stage {stage}",
        )
    except Exception as e:
        logger.warning(f"Could not publish the launch error artifact {key}: {e}")


def _parse_launch_summary(output: str) -> tuple[str, list[SlurmJobId], str] | None:
    """
    Extract (run_id, job_ids, work_dir) from the launch_slurm.py summary block.

    There is one summary line per stage; each line may carry several job ids.
    All lines are expected to share the same run_id and work dir. Returns None
    if no summary line is found, raises ValueError on inconsistent lines.
    """
    run_id: str | None = None
    work_dir: str | None = None
    job_ids: list[SlurmJobId] = []

    for match in _SUMMARY_LINE_RE.finditer(output):
        line_run_id = match.group("run_id")
        line_dir = match.group("dir")
        if run_id is None:
            run_id, work_dir = line_run_id, line_dir
        elif (line_run_id, line_dir) != (run_id, work_dir):
            raise ValueError(
                "Inconsistent summary lines from launch_slurm.py: "
                f"expected run_id={run_id} dir={work_dir}, "
                f"got run_id={line_run_id} dir={line_dir}"
            )
        for token in match.group("job_ids").split(","):
            token = token.strip()
            if token:
                job_ids.append(token)

    if run_id is None or work_dir is None:
        return None
    if not job_ids:
        raise ValueError(f"Summary lines for run_id={run_id} contain no job ids")
    return run_id, job_ids, work_dir


@task
async def launch_slurm(
    ctx: CmdContext,
    wg_private_path: str,
    stage: str,
    from_run_id: str | None = None,
    time: str | None = None,
) -> Result[LaunchSlurm]:
    """
    Launch a sequence of slurm jobs using the weathergenerator
    launch_slurm.py command, and returns the terminal results
    with status of all the launch_slurm jobs.
    """
    # Do not attempt to run expanduser() or resolve(), it runs on the remote HPC
    # and python will not have the appropriate file system information.
    cmd = [str(Path(wg_private_path) / "hpc" / "launch-slurm.py"), "--stage", stage]
    if from_run_id:
        cmd += ["--from-run-id", from_run_id]
    if time:
        cmd += ["--time", time]
    logger = get_run_logger()
    res = await run_cmd(ctx, Command(cmd), logger)
    if is_err(res):
        await _publish_launch_error_artifact(
            logger, stage, from_run_id, f"command failed: {res.err}", res.stdout, res.stderr
        )
        return res
    if res.return_code != 0:
        await _publish_launch_error_artifact(
            logger,
            stage,
            from_run_id,
            f"launch_slurm.py exited with return code {res.return_code}",
            res.stdout,
            res.stderr,
        )
        return OpError(
            err=RuntimeError(f"launch_slurm.py exited with return code {res.return_code}"),
            stdout=res.stdout,
            stderr=res.stderr,
            return_code=res.return_code,
        )

    # Logging may end up on stdout or stderr depending on the handler config,
    # so look in both.
    try:
        parsed = _parse_launch_summary(res.stdout) or _parse_launch_summary(res.stderr)
    except ValueError as e:
        await _publish_launch_error_artifact(
            logger, stage, from_run_id, f"malformed summary block: {e}", res.stdout, res.stderr
        )
        return OpError(err=e, stdout=res.stdout, stderr=res.stderr, return_code=res.return_code)
    if parsed is None:
        await _publish_launch_error_artifact(
            logger,
            stage,
            from_run_id,
            "could not find a summary block in launch_slurm.py output",
            res.stdout,
            res.stderr,
        )
        return OpError(
            err=ValueError("Could not find a summary block in launch_slurm.py output"),
            stdout=res.stdout,
            stderr=res.stderr,
            return_code=res.return_code,
        )
    run_id, slurm_job_ids, wg_work_dir = parsed

    # From that, all the log paths can be reconstructed:
    # {wg_work_dir}/WeatherGenerator/logs/{run_id}/weathergen.part{n+1}.{job_id}.{out,err}
    logs_dir = Path(wg_work_dir) / "WeatherGenerator" / "logs" / run_id
    slurm_jobs = [
        SlurmSubmissionResult(
            job_id=job_id,
            stdout=logs_dir / f"weathergen.part{n + 1}.{job_id}.out",
            stderr=logs_dir / f"weathergen.part{n + 1}.{job_id}.err",
        )
        for n, job_id in enumerate(slurm_job_ids)
    ]

    # Surface the launch details in the Prefect UI as a markdown artifact:
    # all the info in LaunchSlurm plus the launch command's stdout/stderr.
    jobs_md = "\n".join(
        f"| {n + 1} | `{sub.job_id}` | `{sub.stdout}` | `{sub.stderr}` |"
        for n, sub in enumerate(slurm_jobs)
    )
    launch_md = (
        f"## WeatherGenerator launch-slurm\n\n"
        f"- **Run ID:** `{run_id}`\n"
        f"- **Stage:** `{stage}`\n"
        f"- **From run ID:** `{from_run_id}`\n"
        f"- **Work dir:** `{wg_work_dir}`\n\n"
        f"### Jobs\n\n"
        f"| part | job id | stdout | stderr |\n"
        f"| --- | --- | --- | --- |\n"
        f"{jobs_md}\n\n"
        + _output_md_section("launch-slurm.py stdout", res.stdout)
        + _output_md_section("launch-slurm.py stderr", res.stderr)
    )
    await acreate_markdown_artifact(
        key=f"wg-{_artifact_key_part(run_id)}-launch",
        markdown=launch_md,
        description=f"wg run {run_id} stage {stage} launch",
    )

    return LaunchSlurm(
        wg_run_id=run_id,
        stage=stage,
        slurm_jobs=slurm_jobs,
        wg_work_dir=wg_work_dir,
    )


@task
async def wait_for_completion(
    ctx: CmdContext, ls: LaunchSlurm, fetch_output: bool = False
) -> Result[list[SlurmJobResult]]:
    """
    Wait until all the slurm jobs launched by `launch_slurm` reach a terminal
    state, and return their final results (in the same order as `ls.slurm_jobs`).

    The jobs are awaited one after the other: slurm executes them sequentially
    (each part starts after the previous one), so waiting on them in order does
    not add latency.
    """
    logger = get_run_logger()
    _runner = get_command_runner(ctx)
    if isinstance(_runner, Exception):
        return OpError(err=_runner)

    results: list[SlurmJobResult] = []
    for n, sub in enumerate(ls.slurm_jobs):
        logger.info(
            f"Waiting for slurm job {sub.job_id} (run_id={ls.wg_run_id}) on hpc {_runner.hpc}"
        )
        state = await wait_completion_single(logger, ctx, sub.job_id, _runner)
        if is_err(state):
            return state
        logger.info(f"Slurm job {sub.job_id} (run_id={ls.wg_run_id}) finished: {state}")

        # Publish the job details (and optionally its captured logs) in the
        # Prefect UI as a markdown artifact, one per part.
        artifact_key = (
            f"wg-{_artifact_key_part(ls.wg_run_id)}-{_artifact_key_part(ls.stage)}-part{n + 1}"
        )
        job_md = (
            f"## WeatherGenerator slurm job\n\n"
            f"- **Run ID:** `{ls.wg_run_id}`\n"
            f"- **Stage:** `{ls.stage}` (part {n + 1}/{len(ls.slurm_jobs)})\n"
            f"- **Job ID:** `{sub.job_id}`\n"
            f"- **HPC:** `{_runner.hpc}`\n"
            f"- **Status:** `{state}`\n"
            f"- **stdout:** `{sub.stdout}`\n"
            f"- **stderr:** `{sub.stderr}`\n"
        )
        if fetch_output:
            # Fetch head and tail of stdout and stderr for debugging purposes.
            output = get_head_tail_logs(
                ctx=ctx,
                stdout_path=str(sub.stdout),
                stderr_path=str(sub.stderr) if sub.stderr else None,
            )
            logger.info(
                f"Fetched head/tail logs for job {sub.job_id} on hpc {_runner.hpc}: {output}"
            )
            job_md += "\n" + _format_output_section(output)
        await acreate_markdown_artifact(
            key=artifact_key,
            markdown=job_md,
            description=f"wg run {ls.wg_run_id} stage {ls.stage} part {n + 1}",
        )

        results.append(SlurmJobResult(job_id=sub.job_id, status=state, submission=sub))
    return results
