from dataclasses import dataclass

from weathergen.prefect_dags.cmd_runners._exec_cmd import CmdContext
from weathergen.prefect_dags.prefect_wrapper import task
from weathergen.prefect_dags.slurm import SlurmJobId, SlurmJobState
from weathergen.prefect_dags.cmd_runners import (
    CmdContext,
    Command,
    CommandResult,
    run_cmd,
    slurm_account,
)
from weathergen.prefect_dags.result import OpError, Result, is_err
from pathlib import Path

@dataclass
class SlurmJobResult:
    """
    The final result of a slurm job.

    No submission information is included, the submission is 
    done by another process.
    """

    job_id: SlurmJobId
    status: SlurmJobState
    

@dataclass
class LaunchSlurm:
    """
    All the tracking information when using the launch-slurm 
    command. 
    """
    # The run_id generated by the weathergenerator launch-slurm command.
    wg_run_id: str
    slurm_jobs: list[SlurmJobResult]
    # A path to the working dir in weathergenerator.
    wg_work_dir: str

@task
async def launch_slurm(ctx: CmdContext,
                 wg_private_path: str,
                 stage: str,
                 from_run_id: str | None = None) -> Result[LaunchSlurm]:
    """
    Launch a sequence of slurm jobs using the weathergenerator 
    launch_slurm.py command, and returns the terminal results 
    with status of all the launch_slurm jobs.
    """
    cmd = [Path(wg_private_path) / "hpc" / "launch_slurm.py", "--stage", stage
           ]
    if from_run_id:
        cmd += ["--from-run-id", from_run_id]
    res = await run_cmd(ctx, Command(cmd))
    if is_err(res):
        return res
    assert res.stdout, "No output from launch_slurm.py command"
    # TODO: finish to implement
    run_id = "xxx" # TODO
    slurm_job_ids = ["1234"] # TODO
    wg_work_dir = "/xxx" # TODO

    # Wait for the slurm jobs to complete.
    
