global_plotting_options:
  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
  regions: ["global", "arctic"]
  dpi_val : 300
  C-GLORS:
    marker_size: 4

evaluation:
  metrics  : ["froct", "rmse"]
  regions: ["global"]
  summary_plots : true
  summary_dir: "./plots/"
  print_summary: false #print out score values on screen. it can be verbose
  plot_score_maps: true
  log_scale: false
  add_grid: true

run_ids :
  y0mltkag:
    label: "atmofs03-finetune-ycnfjoph"
    epoch: 0
    rank: 0
    streams:
      C-GLORS:
        channels: [
                "icethic",
                "iicevelu",
                "iicevelv",
                "isnowthi",
                "soicecov",
                "sosstsst"]
        evaluation:
          sample: "all"
          forecast_step: "all"
        plotting:
          sample: [0]
          forecast_step: "all"
          plot_maps: true
          plot_animations: true
          plot_histograms: true
