streams:
  SONDES:
    source:
      - obsvalue_t_
      - obsvalue_z_
      - obsvalue_u_
      - obsvalue_v_
      - obsvalue_q_
    target:
      - obsvalue_t_
      - obsvalue_z_
      - obsvalue_u_
      - obsvalue_v_
      - obsvalue_q_
    train_source_channels: null
    train_target_channels: null
    val_source_channels: null
    val_target_channels: null