
streams_directory: "./config/streams/pretrain_analysis_georing_avhrr_synop/"

general:

  # mutable parameters
  istep: 0
  rank: ???
  world_size: ???

training_config:
  num_mini_epochs: 16
  samples_per_mini_epoch: 8192

  context_loss:
    enabled: true
    weight: 1.0
    warmup_steps: 1000             # linear warmup from 0 to weight over this many steps
