training_config:
    losses:
      "student-teacher":
        target_and_aux_calc:
          FrozenTeacher:
            teacher_run_id: "yoqxf234"      # run ID of the pre-trained model
            teacher_mini_epoch: -1            # -1 = latest checkpoint
