global_plotting_options:
  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
  dpi_val : 300
  ERA5:
    marker_size: 5

evaluation:
  metrics  : ["froct", "rmse"]
  regions: ["global"]
  summary_plots : true
  summary_dir: "./plots/"
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: true

run_ids :

  otnh7lcg:
    label: "Control: fine-tune 1979-2022, 8x32 epochs, v1"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  v8bc9sxg:
    label: "fine-tune 2018-2022, 8x32 epochs, v1"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  adja05fc:
    label: "fine-tune 2018-2022, 8x32 epochs, v2"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  nub26n5i:
    label: "fine-tune 2018-2022, seq [4, 6, 8] epochs, v1"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  kl5g92ne:
    label: "fine-tune 2018-2022, seq [4, 6, 8] epochs, v2"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  bwzo5qfn:
    label: "fine-tune 2018-2022, seq [4, 6, 8] epochs, v3"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  jrp2kgem:
    label: "fine-tune 2018-2022, seq [3, 4, ..., 8] epochs, v1"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  ibmenr7o:
    label: "fine-tune 2018-2022, seq [3, 4, ..., 8] epochs, v2"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"

  renlmg1i:
    label: "fine-tune 2018-2022, seq [3, 4, ..., 8] epochs, v3"
    epoch: 0
    rank: 0
    streams:
      ERA5:
        channels: ["2t", "10u", "10v", "q_850", "t_850", "u_850", "v_850", "z_500"]
        evaluation:
          sample: "all"
          forecast_step: "all"
