# Test pipeline for YAML-driven multi-stage Slurm launcher
# Global defaults
nodes: 1
register: true
cleanup-scripts: yes
results-dir: shared
mini-epoch: -1

stages:
  - name: stage1
    command: train
    base-config: ./config/config_jepa_deep_ssl.yml
    config: ./config/config_jepa_deep_ssl.yml
    chain: 1
    nodes: 1

  - name: stage2.1
    command: train-continue
    from: stage1
    config: ./config/config_jepa_finetuning.yml

  - name: stage2.2
    command: train-continue
    config: ./config/config_jepa_forecasting_finetuning.yml
    from: stage1

  - name: inference.1
    command: inference
    from: stage2.1
    samples: 8

  - name: inference.2
    command: inference
    from: stage2.2
    samples: 8
