train:

#pretraining:
  # plot:
  #   qcx8kd41:
  #     slurm_id: 0
  #     description: "N320 - healpix level 6. With Z - 270k samples"
  #   boxi2b73:
  #     slurm_id: 0
  #     description: "N320 - healpix level 5. With Z - 270k samples"

  #iasi finetuning:
  plot:
    g75m3lzp:
      slurm_id: 0
      description: "N320 - healpix level 6. With Z - 270k samples"
    h1y8l4k7 :
      slurm_id: 0
      description: "N320 - healpix level 5. With Z - 270k samples"
    o2qmf3ne:
      slurm_id: 0
      description: "O96 - healpix level 5"
     
  #synop finetuning:
  # plot:
  #   wrxdsq6k:
  #     slurm_id: 0
  #     description: "N320 - healpix level 6"
  #   zmz48o9k:
  #     slurm_id: 0
  #     description: "N320 - healpix level 5"
  #   kcqd250z:
  #     slurm_id: 0
  #     description: "O96 - healpix level 5"
  #   rhxqn6ai:
  #     slurm_id: 0
  #     description: "O96 - healpix level 5. diagnostic = True"
  #   wak5hs2j:
  #     slurm_id: 0
  #     description: "O96 - healpix level 5. diagnostic = True, ERA5 forcing = True"

  #forecast finetuning:
  # plot:
  #   iyn1gl86:
  #     slurm_id: 0
  #     description: "N320 - healpix level 6. With Z - 270k samples"
  #   w3xop4ru:
  #     slurm_id: 0
  #     description: "N320 - healpix level 5. With Z - 270k samples"
  #   mbr736x1:
  #     slurm_id: 0
  #     description: "O96 - healpix level 5 (with Z)"
  