train:
  plot:
    
    # gjl6a0kb:
    #   slurm_id: 0
    #   description: "temporal JEPA pretraining, all years"

    uahdb9yl:
      slurm_id: 0
      description: "temporal JEPA finetuning, all years, continued"

    n0t6ejuo:
      slurm_id: 0
      description: "temporal JEPA finetuning, all years, continued"
    
    # nbx7sema-stage1:
    #   slurm_id: 0
    #   description: "lr, ema: 1.33e-04,587639, save ema state (nbx7nwo3)"
    
    # nbx7stv2-stage1:
    #   slurm_id: 0
    #   description: "lr, ema: 1.33e-04,587639, save model/val ema state too (nbx7nwo3)"

    # op8wojf6-stage1:
    #   slurm_id: 0
    #   description: "lr, ema: 1.46e-04,812034"