train:
  plot:
    # lmx1mi02-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=2.423290e-05, ema=581786, mask=0.2258"
    # a1f3czep-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.572634e-04, ema=316047, mask=0.6744"
    # 2j4kg11h-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=2.136020e-05, ema=287299, mask=0.3698"
    # b71lkrek-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.918856e-05, ema=427352, mask=0.5685"
    # ncypceii-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=6.357724e-05, ema=767257, mask=0.5486"
    # 9ra53elr-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=2.428988e-05, ema=292992, mask=0.5978"
    rlvdnd4c-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 lr=1.223520e-05, ema=908362, mask=0.5065"
    # cxiyigze-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.721862e-05, ema=520636, mask=0.4545"
    # bdi0p17l-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.735844e-04, ema=659829, mask=0.5571"
    # rg80td0n-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.935225e-04, ema=947960, mask=0.5951"
    # qi1e34qe-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.202775e-05, ema=404733, mask=0.2690"
    # vj7xh45i-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.684459e-04, ema=486214, mask=0.5974"
    # bfl0b01w-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.329028e-04, ema=372347, mask=0.2394"
    # g09nlhxx-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.741462e-05, ema=404834, mask=0.6536"
    # v1fqfr4o-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=2.666699e-05, ema=801377, mask=0.6797"
    # 5br1ug5f-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.240294e-04, ema=609724, mask=0.4857"
    # 583ajes2-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=3.424891e-05, ema=562667, mask=0.3459"
    # bsmgqvtw-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.966066e-04, ema=970614, mask=0.3829"
    # w5gxdqkb-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.076520e-04, ema=243152, mask=0.4286"
    # ethnns3t-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=6.984155e-05, ema=398228, mask=0.2304"
    # c61whsnx-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=8.036260e-05, ema=937469, mask=0.2556"
    # ikiiwjkr-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=1.162573e-04, ema=316273, mask=0.4833"
    # ikkrdwqu-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=3.433802e-05, ema=802467, mask=0.6283"
    # e79dlsnj-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=2.434826e-05, ema=986921, mask=0.6015"
    # yyloqgzd-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 lr=3.544830e-05, ema=506672, mask=0.4758"

    ###  Figuring out what changed
    u2fapj0c-stage2.1:
      slurm_id: 0
      description: "V JEPA 2.1 og hparams"
    # vkjm07ro-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 teacher keep rate"
    # ni05wx2y-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 weight decay"
    # lcex6n4d-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 revert deep ssl layers"
    # pv3m1jcr-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 global vs query layers"
    # olkth2qi-finetune:
    #   slurm_id: 0
    #   description: "V JEPA 2.1 fix context loss"
    ek2d37lt-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix v2 context loss"
    bd2jbn47-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix teacher-mask-rate=0.2"
    u9bnkti5-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix teacher-mask-rate=0.4"
    i6yznmlk-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix teacher-mask-rate=0.6"
    faxnwkvf-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix teacher-mask-rate=0.8"
    tcknh0q9-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix teacher-mask-rate=1.0"
    ffms36l7-finetune:
      slurm_id: 0
      description: "V JEPA 2.1 fix cropping-mask-rate=0.6"

