train:
  plot:
    # l5mdil6s-stage1:
    #   slurm_id: 0
    #   description: "Previous Temporal JEPA"
    # nbx7stv2-stage1:
    #   slurm_id: 0
    #   description: "Best of Seb April 9th"
    ju4t5mo9-pretrain:
      slurm_id: 0
      description: "New arch with noise at forecasting"
    o1gchykd-pretrain:
      slurm_id: 0
      description: "New arch without noise at forecasting"

