train:
  plot:
    ju4t5mo9-finetune:
      slurm_id: 0
      description: "Space JEPA previous (with noise)"
    ju4t5mo9-finetune:
      slurm_id: 0
      description: "Space JEPA previous (with noise)"
    o1gchykd-finetune:
      slurm_id: 0
      description: "Space JEPA previous"
    # vvmprn2j-finetune-forecast:
    #   slurm_id: 0
    #   description: "Space JEPA longer training lr=1e-4"
    # g3mqvfl0-finetune-forecast:
    #   slurm_id: 0
    #   description: "Space JEPA longer training lr=7e-5"
    # f41lnpxo-finetune-forecast:
    #   slurm_id: 0
    #   description: "Space JEPA longer training lr=5e-5"
    # tbyrqf7k-finetune-forecast:
    #   slurm_id: 0
    #   description: "Space JEPA longer training lr=3e-5"
    # fydspoa2-finetune-forecast:
    #   slurm_id: 0
    #   description: "Space JEPA longer training lr=1e-5"
    c9bgfa31-finetune:
      slurm_id: 0
      description: "Space JEPA fix register fix reduction (with noise)"
    # Just bad
    # fgtc6md2-finetune:
    #   slurm_id: 0
    #   description: "Space JEPA ERA5 + GEO H512"
    b2iq8rvw-finetune:
      slurm_id: 0
      description: "Space JEPA ERA5 + GEO H512"
    f7madnkb-finetune:
      slurm_id: 0
      description: "Space JEPA Mask_rate=0.7"
    wz0qitek-finetune:
      slurm_id: 0
      description: "Space JEPA Mask_rate=0.4"
    f9b7dihn-finetune:
      slurm_id: 0
      description: "Space JEPA Mask_rate=0.5"
    fn2krsa5-finetune:
      slurm_id: 0
      description: "Space JEPA context_loss=0.6"
    xp8szbm9-finetune:
      slurm_id: 0
      description: "Space JEPA context_loss=0.4"


