# (C) Copyright 2025 WeatherGenerator contributors.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

from __future__ import annotations  # allow forward references in typehints

import dataclasses
import itertools
import pathlib
import typing
from collections.abc import Callable

import numpy as np

from weathergen.common.config import Config
from weathergen.common.io import (
    DSKind,
    IOReaderData,
    ItemKey,
    OutputDataset,
    OutputItem,
    TimeRange,
    ZarrIO,
    zarrio_writer,
)
from weathergen.datasets.batch import ModelBatch
from weathergen.model.model import ModelOutput
from weathergen.train.target_and_aux_module_base import PhysicalTarget, TargetAuxOutput

_LAST_INPUT_STEP_IDX = 0


class Writer:
    """
    Write WeatherGenerator output that is chunked into OutputItems to a storage backend.
    """

    def __init__(
        self, mode_cfg: Config, streams_config: list[Config], inference_result_path: pathlib.Path
    ):
        """
        Initialize a new writer, should be done in a context manager.

        Args:
            mode_cfg: mode config to infer output streams and forecast offset.
            streams_config: stream configs to infer e.g. channel names.
            inference_result_path: Path to a physical storage destination
              used by the storage backend.
        """
        streams = {stream.name: stream for stream in streams_config}

        # TODO: do this in config
        _output_streams = mode_cfg.get("output", {}).get("streams")
        _output_streams = list(streams.keys()) if _output_streams is None else _output_streams
        self._forecast_offset = mode_cfg.get("forecast", {}).get("offset", 0)

        self._streams = {
            name: config for name, config in streams.items() if name in _output_streams
        }
        self._zio: ZarrIO = zarrio_writer(inference_result_path)

    def __enter__(self):
        self._zio = self._zio.__enter__()
        return self

    def __exit__(self, exc_type, exc_value, exc_tb):
        self._zio.__exit__(exc_type, exc_value, exc_tb)

    def write_batch(
        self,
        batch: ModelBatch,
        targets: TargetAuxOutput,
        predictions: ModelOutput,
        denormalizer: typing.Callable,  # TODO store in TargetAuxOutput/ModelOutput,
    ) -> None:
        """
        Write WeatherGenerator output in chunks to a storage backend.

        Exactly one OutputItem will be extracted and written for the cartesian product of
        `streams` x `samples` x `forecast steps`. The storage backend treats the elements
        of the product as unique keys. Attempts to rewrite data for a key will result in
        failure.

        Args:
            batch: Sampling data generated by MultiStreamDataSampler.
              One batch is always associated with one original time window,
              but can have multiple samples sampled within that window.
            targets: TargetAuxCalculator might augment the target data found in the batch.
              That is why we take separate target data in form of a TargetAuxOutput instance.
            predictions: Output generated by a forward pass of the WeatherGenerator model.
            denormalizer: Function to normalize predictions and targets. Will be passed through.
        """
        data = _BatchOutputData(batch, targets, predictions, denormalizer)

        assert self._zio.data_root is not None, (
            "Storage backend not initialized, use Writer in a contextmanager."
        )

        for key in self.keys(data.fsteps, data.samples, self._streams.keys()):
            self._zio.write_zarr(self._extract(data, key))

    def _extract(self, data: _BatchOutputData, key: ItemKey) -> OutputItem:
        """Construct the OutputItem for the given ItemKey from the model data."""
        data_invariants = self._get_channel_information(key.stream)
        # TODO unify DTRange and TimeRange classes
        data_invariants.source_interval = data.source_interval

        datasets = {}
        if key.with_source:
            datasets[DSKind.source] = data.extract_source(key).as_dataset(key, data_invariants)
        if key.with_prediction(self._forecast_offset):
            datasets[DSKind.target] = data.extract_target(key).as_dataset(key, data_invariants)
            datasets[DSKind.prediction] = data.extract_prediction(key).as_dataset(
                key, data_invariants
            )

        return OutputItem(key, datasets, self._forecast_offset)

    def _get_channel_information(self, stream: str) -> _DataInvariants:
        """Gather channel names for a stream."""
        return _DataInvariants(
            # val_source_channels are ListConfig[str] objects -> convert to list[str]
            source_channels=list(self._streams[stream].val_source_channels),
            target_channels=list(self._streams[stream].val_target_channels),
            geoinfo_channels=list(self._streams[stream].geoinfo_channels),
        )

    @staticmethod
    def keys(
        forecast_steps: typing.Iterable[int],
        samples: typing.Iterable[int],
        streams: typing.Iterable[str],
    ) -> typing.Generator[ItemKey, None, None]:
        """
        Generate Itemkeys for the cartesian product of `streams` x `samples` x `forecast steps`.

        The combinations generated here should be unique.

        Args:
          forecast_steps: forecast steps to write.
          sampls: unique indices for all samples accross all batches within one rank.
          streams: only write these streams.
        """
        assert len(set(streams)) == len(streams), "streams are not unique"
        assert len(set(forecast_steps)) == len(forecast_steps), "fsteps are not unique"
        assert len(set(samples)) == len(samples), "samples are not unique"

        # The order of iteration is important here:
        # streams is the outermost and samples the innermost loop variable
        # This is important since normalization is best done at a per stream/fstep basis
        for stream, forecast_step, sample_idx in itertools.product(
            streams, forecast_steps, samples
        ):
            yield ItemKey(sample_idx, forecast_step, stream)


class _BatchOutputData:
    """
    Provide access to model source, targets and predictions datastructures.

    Attrs:
      source_interval: Time window that sources are sampled from.
      samples: Unique sample indices accross all batches for the samples within this batch.
    """

    def __init__(
        self,
        batch: ModelBatch,
        targets: TargetAuxOutput,
        predictions: ModelOutput,
        denormalizer: Callable[[str, np.ArrayLike], np.ArrayLike],
    ):
        """
        Initialize a new intstance.

        Args:
          batch: source data
          targets: target data
          predictions: prediction results
          denormalizer: function to denormalize targets and predictions.
        """
        self._batch = batch
        self._targets = targets
        self._predictions = predictions
        self._denormalizer = denormalizer  # TODO register normalizer in Target

        # get target samples
        raw_samples = np.unique(self._batch.source2target_matching_idxs)
        self._sample_offset: int = self._batch.idx * len(raw_samples)

        # TODO add a attribute on ModelBatch to track incremental forecasting
        self._fstep_offset: int = 0

        _window = self._batch.source_time_range
        self.source_interval: TimeRange = TimeRange(_window.start, _window.end)
        self.samples = [sample + self._sample_offset for sample in raw_samples]

    @property
    def fsteps(self) -> typing.Iterable[int]:
        """Forecast steps to be written."""
        output_idxs = self._batch.get_output_idxs()
        # ensure that source step is always written
        source_idx = [] if 0 in output_idxs else [0]
        return source_idx + [fstep + self._fstep_offset for fstep in self._batch.get_output_idxs()]

    def extract_source(self, key: ItemKey) -> _ExtractedData:
        """Extract source data needed to construct a OutputDataset."""
        raw_key = self._raw_key(key)
        source_sample_idx = self._batch.target2source_matching_idxs[raw_key.sample]
        assert len(source_sample_idx) == 1, "Source sample expected to be unique."
        source_sample_idx = source_sample_idx[0]
        source: IOReaderData = (
            self._batch.source_samples.samples[source_sample_idx]
            .streams_data[raw_key.stream]
            .source_raw[_LAST_INPUT_STEP_IDX]
        )
        if source.is_empty():  # data exists but is spoofed
            assert source.is_spoof  # if empty it should be spoofed
            source.data = None  # discard spoofed data

        return _ExtractedData(
            DSKind.source,
            np.asarray(source.data),
            np.asarray(source.datetimes),
            np.asarray(source.coords),
            np.asarray(source.geoinfos),
        )

    def extract_target(self, key: ItemKey) -> _ExtractedData:
        """Extract target data needed to construct a OutputDataset."""
        raw_key = self._raw_key(key)
        target = self._target(raw_key)
        coords = self._target_coordinates(target)

        return _ExtractedData(
            DSKind.target, target.data, coords.times, coords.coords, coords.geoinfos
        )

    def extract_prediction(self, key: ItemKey) -> _ExtractedData:
        """Extract prediction data needed to construct a OutputDataset."""
        raw_key = self._raw_key(key)
        data = self._predictions.get_physical_prediction_normalized(raw_key, self._denormalizer)
        target = self._target(raw_key)
        coords = self._target_coordinates(target)

        return _ExtractedData(DSKind.prediction, data, coords.times, coords.coords, coords.geoinfos)

    def _target(self, raw_key: ItemKey) -> PhysicalTarget:
        return self._targets.get_physical_target_normalized(raw_key, self._denormalizer)

    def _target_coordinates(self, target: PhysicalTarget) -> _ExtractedData:
        """Extract target coordinate data (spatial, temporal, geoinfo)."""
        return _ExtractedData(DSKind.target, None, target.datetimes, target.coords, target.geoinfos)

    def _raw_key(self, key: ItemKey) -> ItemKey:
        """Get key indices for indexing into buffers from globaly unique indices."""
        return ItemKey(
            key.sample - self._sample_offset, key.forecast_step - self._fstep_offset, key.stream
        )


@dataclasses.dataclass
class _DataInvariants:
    source_channels: list[str]
    target_channels: list[str]
    geoinfo_channels: list[str]
    source_interval: TimeRange | None = None


@dataclasses.dataclass
class _ExtractedData:
    name: DSKind
    data: np.NDArray | None
    times: np.NDArray
    coords: np.NDArray
    geoinfos: np.NDArray

    def as_dataset(self, key: ItemKey, invariants: _DataInvariants) -> OutputDataset:
        channels = (
            invariants.source_channels if self.name == DSKind.source else invariants.target_channels
        )
        if self.data is None or self.data.shape[0] == 0:
            return None  # discard empty sources/targets/predictions
        else:
            return OutputDataset(
                name=self.name,
                item_key=key,
                data=self.data,
                times=self.times,
                coords=self.coords,
                geoinfo=self.geoinfos,
                source_interval=invariants.source_interval,
                channels=channels,
                geoinfo_channels=invariants.geoinfo_channels,
            )
