model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 1.26e-04
  losses:
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 253395

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: syjgf2s1
  lr_max: "1.26e-04"
  ema_halflife: "253395"
