model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 8.75e-05
  losses:
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 757619

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: s1udkjvi
  lr_max: "8.75e-05"
  ema_halflife: "757619"
