model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 9.70e-05
  losses:
    physical:
      loss_fcts:
        kernel_crps:
          weight: 0.446
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 524278

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: qav8wdia
  lr_max: "9.70e-05"
  ema_halflife: "524278"
  kernel_crps_weight: "0.446"
