model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 1.09e-04
  losses:
    physical:
      loss_fcts:
        kernel_crps:
          weight: 0.673
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 942407

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: qzb43ev0
  lr_max: "1.09e-04"
  ema_halflife: "942407"
  kernel_crps_weight: "0.673"
