model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 8.18e-05
  losses:
    physical:
      loss_fcts:
        kernel_crps:
          weight: 0.421
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 884048

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: qdqzwd1u
  lr_max: "8.18e-05"
  ema_halflife: "884048"
  kernel_crps_weight: "0.421"
