model_path: "./models"

training_config:
  learning_rate_scheduling:
    lr_max: 8.77e-05
  losses:
    physical:
      loss_fcts:
        kernel_crps:
          weight: 0.503
    student-teacher:
      target_and_aux_calc:
        EMATeacher:
          ema_halflife_in_thousands: 982823

wgtags:
  exp: jepa_latent_forecast_sweep
  parent_run: q97777zf
  lr_max: "8.77e-05"
  ema_halflife: "982823"
  kernel_crps_weight: "0.503"
