#!/usr/bin/env python3
"""
Generate baseline configs for uniform HEALPix masking (no per-channel masking).

Creates training configs where ALL variables share the same hl_mask level.
These serve as baselines for comparison against per-channel masking ablations.

Usage:
    python scripts/generate_uniform_masking_baselines.py

Configs generated:
  - config_uniform_hl1.yml  (hl_mask=1, coarsest, ~1833 km cells)
  - config_uniform_hl2.yml  (hl_mask=2, ~916 km cells)
  - config_uniform_hl3.yml  (hl_mask=3, ~458 km cells)
  - config_uniform_hl4.yml  (hl_mask=4, ~229 km cells)
  - config_uniform_hl5.yml  (hl_mask=5, finest, ~115 km cells — same as data level)
  - config_uniform_random.yml  (random masking, no spatial structure)
"""

from pathlib import Path


def generate_stream_config() -> str:
    """Generate a simple ERA5 stream config without channel_masking."""
    return """\
# ERA5 stream for uniform masking baselines (no per-channel masking).
# Generated by scripts/generate_uniform_masking_baselines.py

ERA5 :
  type : anemoi
  filenames : ['aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr']
  stream_id : 0
  source_exclude : ['w_', 'skt', 'tcw', 'cp', 'tp']
  target_exclude : ['w_', 'slor', 'sdor', 'tcw', 'cp', 'tp']
  loss_weight : 1.
  location_weight : cosine_latitude
  masking_rate : 0.6
  masking_rate_none : 0.05
  token_size : 8
  tokenize_spacetime : True
  max_num_targets: -1

  embed :
    net : transformer
    num_tokens : 1
    num_heads : 8
    dim_embed : 256
    num_blocks : 2
  embed_target_coords :
    net : linear
    dim_embed : 256
  target_readout :
    type : 'obs_value'
    num_layers : 2
    num_heads : 4
  pred_head :
    ens_size : 1
    num_layers : 1
"""


def generate_training_config(hl_mask: int | None, strategy: str) -> str:
    """Generate a training config for uniform masking at a given HEALPix level.

    Args:
        hl_mask: HEALPix masking level (1-5), or None for random masking.
        strategy: "healpix" or "random".
    """
    if strategy == "random":
        label = "random"
        desc = "uniform_random"
        strategy_config = '{ rate: 0.5, rate_sampling: False }'
    else:
        label = f"hl{hl_mask}"
        desc = f"uniform_hl{hl_mask}"
        strategy_config = f'{{ rate: 0.5, hl_mask: {hl_mask}, rate_sampling: False }}'

    return f"""\
# Training config for uniform {strategy} masking{f" at HEALPix level {hl_mask}" if hl_mask else ""}.
# No per-channel masking — all variables share the same mask.
# Generated by scripts/generate_uniform_masking_baselines.py

embed_orientation: "channels"
embed_unembed_mode: "block"
embed_dropout_rate: 0.1

ae_local_dim_embed: 512
ae_local_num_blocks: 2
ae_local_num_heads: 16
ae_local_dropout_rate: 0.1
ae_local_with_qk_lnorm: True

ae_local_num_queries: 1
ae_local_queries_per_cell: False
ae_adapter_num_heads: 16
ae_adapter_embed: 128
ae_adapter_with_qk_lnorm: True
ae_adapter_with_residual: True
ae_adapter_dropout_rate: 0.1

ae_global_dim_embed: 512
ae_global_num_blocks: 2
ae_global_num_heads: 32
ae_global_dropout_rate: 0.1
ae_global_with_qk_lnorm: True
ae_global_att_dense_rate: 1.0
ae_global_block_factor: 64
ae_global_mlp_hidden_factor: 2
ae_global_trailing_layer_norm: False

ae_aggregation_num_blocks: 2
ae_aggregation_num_heads: 32
ae_aggregation_dropout_rate: 0.1
ae_aggregation_with_qk_lnorm: True
ae_aggregation_att_dense_rate: 1.0
ae_aggregation_block_factor: 64
ae_aggregation_mlp_hidden_factor: 2

decoder_type: PerceiverIOCoordConditioning
pred_adapter_kv: False
pred_self_attention: True
pred_dyadic_dims: False
pred_mlp_adaln: True
num_class_tokens: 1
num_register_tokens: 7

fe_num_blocks: 6
fe_num_heads: 16
fe_dropout_rate: 0.1
fe_with_qk_lnorm: True
fe_layer_norm_after_blocks: []
fe_impute_latent_noise_std: 0.0
forecast_att_dense_rate: 1.0

healpix_level: 5

with_mixed_precision: True
with_flash_attention: True
compile_model: False
with_fsdp: True
attention_dtype: bf16
mixed_precision_dtype: bf16
mlp_norm_eps: 1e-5
norm_eps: 1e-4

latent_noise_kl_weight: 0.0
latent_noise_gamma: 2.0
latent_noise_saturate_encodings: 5
latent_noise_use_additive_noise: False
latent_noise_deterministic_latents: True

freeze_modules: ""
norm_type: "LayerNorm"
zarr_store: "zip"

#####################################

streams_directory: "./config/streams/era5_1deg/"
streams: ["era5_uniform_masking.yml"]

general:
  istep: 0
  rank: ???
  world_size: ???
  multiprocessing_method: "fork"
  desc: "{desc}"
  run_id: ???
  run_history: []

train_log_freq:
  terminal: 10
  metrics: 20
  checkpoint: 250

data_loading:
  num_workers: 12
  rng_seed: ???
  repeat_data_in_mini_epoch: False
  memory_pinning: True

training_config:
  training_mode: ["masking"]

  num_mini_epochs: 32
  samples_per_mini_epoch: 4096
  shuffle: True

  start_date: 1979-01-01T00:00
  end_date: 2022-12-31T00:00

  time_window_step: 06:00:00
  time_window_len: 06:00:00
  window_offset_prediction: 1

  learning_rate_scheduling:
    lr_start: 1e-6
    lr_max: 5e-5
    lr_final_decay: 1e-6
    lr_final: 0.0
    num_steps_warmup: 512
    num_steps_cooldown: 512
    policy_warmup: "cosine"
    policy_decay: "constant"
    policy_cooldown: "linear"
    parallel_scaling_policy: "sqrt"

  optimizer:
    grad_clip: 1.0
    weight_decay: 0.1
    log_grad_norms: False
    adamw:
      beta1: 0.975
      beta2: 0.9875
      eps: 2e-08

  losses: {{
    "physical": {{
        type: LossPhysical,
        loss_fcts: {{ "mse": {{ }}, }},
        }},
    }}

  model_input: {{
    "masking": {{
      masking_strategy: "{strategy}",
      num_samples: 1,
      masking_strategy_config: {strategy_config}
      }},
    }}

  forecast:
    time_step: 06:00:00
    num_steps: 1
    policy: "fixed"

validation_config:
  samples_per_mini_epoch: 256
  shuffle: False
  start_date: 2023-10-01T00:00
  end_date: 2023-12-31T00:00

  validate_with_ema:
    enabled: True
    ema_ramp_up_ratio: 0.09
    ema_halflife_in_thousands: 1e-3

  write_num_samples: 0
  output_streams: null
  validate_before_training: False

wgtags:
  org: null
  issue: null
  exp: "uniform_masking_ablation"
  grid: null
"""


def main():
    base = Path(__file__).resolve().parent.parent
    stream_dir = base / "config" / "streams" / "era5_1deg"
    config_dir = base / "config"

    # Write shared stream config (no channel_masking)
    stream_path = stream_dir / "era5_uniform_masking.yml"
    stream_path.write_text(generate_stream_config())
    print(f"Stream config: {stream_path.name}")

    # Generate HEALPix masking at levels 1-5
    configs = []
    for hl in range(1, 6):
        path = config_dir / f"config_uniform_hl{hl}.yml"
        path.write_text(generate_training_config(hl_mask=hl, strategy="healpix"))
        configs.append((f"hl{hl}", path.name))

    # Generate random masking baseline
    path = config_dir / "config_uniform_random.yml"
    path.write_text(generate_training_config(hl_mask=None, strategy="random"))
    configs.append(("random", path.name))

    print(f"\nGenerated {len(configs)} training configs:")
    for label, name in configs:
        print(f"  {label:>8} -> {name}")

    print("\nTo train each baseline:")
    for label, name in configs:
        print(f"  uv run train --config config/{name}")


if __name__ == "__main__":
    main()
