#!/usr/bin/env python3
"""
Generate ablation configs for the channel masking multiplier.

Creates paired stream + training configs for each multiplier value.
The multiplier controls: L_mask = multiplier * L_corr, which determines
the HEALPix masking level for each variable.

Usage:
    python scripts/generate_multiplier_ablation.py

HEALPix cell sizes (reference):
  Level 1: ~1833 km, Level 2: ~916 km, Level 3: ~458 km,
  Level 4: ~229 km,  Level 5: ~115 km

Expected level distribution across multipliers (88 variables):
  mult  | hl1  hl2  hl3  hl4  hl5 | effect
  0.25  |  43    9   21    8    7  | fine — many vars at hl3-5
  0.50  |  53   14   17    4    0  | moderate-fine
  0.75  |  62   10   15    1    0  | balanced
  1.00  |  66   12   10    0    0  | natural scale (mask = L_corr)
  1.50  |  73    9    5    1    0  | current default, mostly coarse
  2.00  |  78    6    4    0    0  | all coarse
"""

import math
from pathlib import Path

EARTH_R = 6371.0

# Multiplier search space
MULTIPLIERS = [0.25, 0.50, 0.75, 1.00, 1.50, 2.00]

# Autocorrelation data from compute_autocorr.py (all 88 variables)
AUTOCORR = {
    "10u": 1040, "10v": 620, "2d": 122990, "2t": 500, "cp": 1650,
    "msl": 1630, "q_100": 2180, "q_1000": 6470, "q_150": 3430,
    "q_200": 2800, "q_250": 2320, "q_300": 1970, "q_400": 1760,
    "q_50": 3480, "q_500": 1880, "q_600": 2220, "q_700": 2710,
    "q_850": 4110, "q_925": 5930, "skt": 500, "sp": 8210,
    "t_100": 5660, "t_1000": 19240, "t_150": 4740, "t_200": 2380,
    "t_250": 7820, "t_300": 11810, "t_400": 12390, "t_50": 6420,
    "t_500": 13380, "t_600": 15070, "t_700": 19900, "t_850": 19330,
    "t_925": 18460, "tcw": 4270, "tp": 1390,
    "u_100": 1760, "u_1000": 1070, "u_150": 1210, "u_200": 1070,
    "u_250": 1030, "u_300": 1040, "u_400": 1110, "u_50": 3280,
    "u_500": 1220, "u_600": 1280, "u_700": 1320, "u_850": 1190,
    "u_925": 1080,
    "v_100": 790, "v_1000": 590, "v_150": 620, "v_200": 510,
    "v_250": 490, "v_300": 500, "v_400": 520, "v_50": 900,
    "v_500": 530, "v_600": 530, "v_700": 520, "v_850": 530,
    "v_925": 540,
    "w_100": 710, "w_1000": 500, "w_150": 900, "w_200": 630,
    "w_250": 470, "w_300": 450, "w_400": 260, "w_50": 1860,
    "w_500": 310, "w_600": 590, "w_700": 900, "w_850": 9550,
    "w_925": 19830,
    "z_100": 42460, "z_1000": 1990, "z_150": 21650, "z_200": 17240,
    "z_250": 15490, "z_300": 14690, "z_400": 13910, "z_50": 64560,
    "z_500": 12980, "z_600": 11500, "z_700": 9410, "z_850": 5330,
    "z_925": 3300,
}

# Variable groups for the YAML
GROUPS = [
    ("Geopotential height", ["z_50", "z_100", "z_150", "z_200", "z_250", "z_300",
                              "z_400", "z_500", "z_600", "z_700", "z_850", "z_925", "z_1000"]),
    ("Temperature", ["t_50", "t_100", "t_150", "t_200", "t_250", "t_300",
                      "t_400", "t_500", "t_600", "t_700", "t_850", "t_925", "t_1000"]),
    ("Specific humidity", ["q_50", "q_100", "q_150", "q_200", "q_250", "q_300",
                            "q_400", "q_500", "q_600", "q_700", "q_850", "q_925", "q_1000"]),
    ("Zonal wind", ["u_50", "u_100", "u_150", "u_200", "u_250", "u_300",
                     "u_400", "u_500", "u_600", "u_700", "u_850", "u_925", "u_1000"]),
    ("Meridional wind", ["v_50", "v_100", "v_150", "v_200", "v_250", "v_300",
                          "v_400", "v_500", "v_600", "v_700", "v_850", "v_925", "v_1000"]),
    ("Surface / single-level", ["10u", "10v", "2t", "2d", "sp", "msl",
                                 "skt", "tcw", "tp", "cp"]),
    ("Vertical velocity (excluded)", ["w_50", "w_100", "w_150", "w_200", "w_250", "w_300",
                                       "w_400", "w_500", "w_600", "w_700", "w_850", "w_925", "w_1000"]),
]


def cell_size_km(h: int) -> float:
    n_cells = 12 * (4**h)
    return math.sqrt((4 * math.pi * EARTH_R**2) / n_cells)


def corr_to_hl(l_corr: float, mult: float, hl_min: int = 1, hl_max: int = 5) -> int:
    target = l_corr * mult
    for hl in range(hl_max, hl_min - 1, -1):
        if cell_size_km(hl) > target:
            return hl
    return hl_min


def mult_tag(m: float) -> str:
    """Convert multiplier to filename-safe tag, e.g. 0.25 -> '025', 1.5 -> '150'."""
    return f"{m * 100:.0f}".zfill(3)


def generate_stream_config(multiplier: float) -> str:
    """Generate a stream YAML config for the given multiplier."""
    tag = mult_tag(multiplier)
    lines = []
    lines.append(f"# ERA5 stream with channel_masking (multiplier={multiplier})")
    lines.append(f"# Generated by scripts/generate_multiplier_ablation.py")
    lines.append("")
    lines.append(f"ERA5 :")
    lines.append(f"  type : anemoi")
    lines.append(f"  filenames : ['aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v8.zarr']")
    lines.append(f"  stream_id : 0")
    lines.append(f"  source_exclude : ['w_', 'skt', 'tcw', 'cp', 'tp']")
    lines.append(f"  target_exclude : ['w_', 'slor', 'sdor', 'tcw', 'cp', 'tp']")
    lines.append(f"  loss_weight : 1.")
    lines.append(f"  location_weight : cosine_latitude")
    lines.append(f"  masking_rate : 0.6")
    lines.append(f"  masking_rate_none : 0.05")
    lines.append(f"  token_size : 8")
    lines.append(f"  tokenize_spacetime : True")
    lines.append(f"  max_num_targets: -1")
    lines.append("")
    lines.append(f"  channel_masking:")
    lines.append(f"    enabled: true")
    lines.append(f"    autocorr:")

    for group_name, var_names in GROUPS:
        lines.append(f"      # ---- {group_name} ----")
        for v in var_names:
            if v in AUTOCORR:
                hl = corr_to_hl(AUTOCORR[v], mult=multiplier)
                lines.append(f"      {v + ':':8s} {{space_km: {AUTOCORR[v]:>5d}}}    # level {hl}")

    lines.append(f"    multiplier: {multiplier}")
    lines.append(f"    hl_mask_min: 1")
    lines.append(f"    hl_mask_max: 5")
    lines.append(f"    default_hl_mask: 3")
    lines.append("")
    lines.append(f"  embed :")
    lines.append(f"    net : transformer")
    lines.append(f"    num_tokens : 1")
    lines.append(f"    num_heads : 8")
    lines.append(f"    dim_embed : 256")
    lines.append(f"    num_blocks : 2")
    lines.append(f"  embed_target_coords :")
    lines.append(f"    net : linear")
    lines.append(f"    dim_embed : 256")
    lines.append(f"  target_readout :")
    lines.append(f"    type : 'obs_value'")
    lines.append(f"    num_layers : 2")
    lines.append(f"    num_heads : 4")
    lines.append(f"  pred_head :")
    lines.append(f"    ens_size : 1")
    lines.append(f"    num_layers : 1")
    lines.append("")

    return "\n".join(lines)


def generate_training_config(multiplier: float) -> str:
    """Generate a training YAML config for the given multiplier."""
    tag = mult_tag(multiplier)
    stream_file = f"era5_cm_mult{tag}.yml"

    return f"""# Training config for channel_masking multiplier ablation (mult={multiplier})
# Generated by scripts/generate_multiplier_ablation.py

embed_orientation: "channels"
embed_unembed_mode: "block"
embed_dropout_rate: 0.1

ae_local_dim_embed: 512
ae_local_num_blocks: 2
ae_local_num_heads: 16
ae_local_dropout_rate: 0.1
ae_local_with_qk_lnorm: True

ae_local_num_queries: 1
ae_local_queries_per_cell: False
ae_adapter_num_heads: 16
ae_adapter_embed: 128
ae_adapter_with_qk_lnorm: True
ae_adapter_with_residual: True
ae_adapter_dropout_rate: 0.1

ae_global_dim_embed: 512
ae_global_num_blocks: 2
ae_global_num_heads: 32
ae_global_dropout_rate: 0.1
ae_global_with_qk_lnorm: True
ae_global_att_dense_rate: 1.0
ae_global_block_factor: 64
ae_global_mlp_hidden_factor: 2
ae_global_trailing_layer_norm: False

ae_aggregation_num_blocks: 2
ae_aggregation_num_heads: 32
ae_aggregation_dropout_rate: 0.1
ae_aggregation_with_qk_lnorm: True
ae_aggregation_att_dense_rate: 1.0
ae_aggregation_block_factor: 64
ae_aggregation_mlp_hidden_factor: 2

decoder_type: PerceiverIOCoordConditioning
pred_adapter_kv: False
pred_self_attention: True
pred_dyadic_dims: False
pred_mlp_adaln: True
num_class_tokens: 1
num_register_tokens: 7

fe_num_blocks: 6
fe_num_heads: 16
fe_dropout_rate: 0.1
fe_with_qk_lnorm: True
fe_layer_norm_after_blocks: []
fe_impute_latent_noise_std: 0.0
forecast_att_dense_rate: 1.0

healpix_level: 5

with_mixed_precision: True
with_flash_attention: True
compile_model: False
with_fsdp: True
attention_dtype: bf16
mixed_precision_dtype: bf16
mlp_norm_eps: 1e-5
norm_eps: 1e-4

latent_noise_kl_weight: 0.0
latent_noise_gamma: 2.0
latent_noise_saturate_encodings: 5
latent_noise_use_additive_noise: False
latent_noise_deterministic_latents: True

freeze_modules: ""
norm_type: "LayerNorm"
zarr_store: "zip"

#####################################

streams_directory: "./config/streams/era5_1deg/"
streams: ["{stream_file}"]

general:
  istep: 0
  rank: ???
  world_size: ???
  multiprocessing_method: "fork"
  desc: "cm_mult{tag}"
  run_id: ???
  run_history: []

train_log_freq:
  terminal: 10
  metrics: 20
  checkpoint: 250

data_loading:
  num_workers: 12
  rng_seed: ???
  repeat_data_in_mini_epoch: False
  memory_pinning: True

training_config:
  training_mode: ["masking"]

  num_mini_epochs: 32
  samples_per_mini_epoch: 4096
  shuffle: True

  start_date: 1979-01-01T00:00
  end_date: 2022-12-31T00:00

  time_window_step: 06:00:00
  time_window_len: 06:00:00
  window_offset_prediction: 1

  learning_rate_scheduling:
    lr_start: 1e-6
    lr_max: 5e-5
    lr_final_decay: 1e-6
    lr_final: 0.0
    num_steps_warmup: 512
    num_steps_cooldown: 512
    policy_warmup: "cosine"
    policy_decay: "constant"
    policy_cooldown: "linear"
    parallel_scaling_policy: "sqrt"

  optimizer:
    grad_clip: 1.0
    weight_decay: 0.1
    log_grad_norms: False
    adamw:
      beta1: 0.975
      beta2: 0.9875
      eps: 2e-08

  losses: {{
    "physical": {{
        type: LossPhysical,
        loss_fcts: {{ "mse": {{ }}, }},
        }},
    }}

  model_input: {{
    "masking": {{
      masking_strategy: "healpix",
      num_samples: 1,
      masking_strategy_config: {{ rate: 0.5, hl_mask: 2, rate_sampling: False }}
      }},
    }}

  forecast:
    time_step: 06:00:00
    num_steps: 1
    policy: "fixed"

validation_config:
  samples_per_mini_epoch: 256
  shuffle: False
  start_date: 2023-10-01T00:00
  end_date: 2023-12-31T00:00

  validate_with_ema:
    enabled: True
    ema_ramp_up_ratio: 0.09
    ema_halflife_in_thousands: 1e-3

  write_num_samples: 0
  output_streams: null
  validate_before_training: False

wgtags:
  org: null
  issue: null
  exp: "cm_mult_ablation"
  grid: null
"""


def main():
    base = Path(__file__).resolve().parent.parent
    stream_dir = base / "config" / "streams" / "era5_1deg"
    config_dir = base / "config"

    print("Generating multiplier ablation configs...")
    print(f"  Stream dir: {stream_dir}")
    print(f"  Config dir: {config_dir}")
    print()

    for m in MULTIPLIERS:
        tag = mult_tag(m)

        # Compute level distribution for summary
        counts = {hl: 0 for hl in range(1, 6)}
        for v, l in AUTOCORR.items():
            counts[corr_to_hl(l, mult=m)] += 1
        dist = " | ".join(f"hl{hl}={counts[hl]}" for hl in range(1, 6))

        # Write stream config
        stream_path = stream_dir / f"era5_cm_mult{tag}.yml"
        stream_path.write_text(generate_stream_config(m))

        # Write training config
        config_path = config_dir / f"config_cm_mult{tag}.yml"
        config_path.write_text(generate_training_config(m))

        print(f"  mult={m:<4} -> {stream_path.name}, {config_path.name}  [{dist}]")

    print(f"\nGenerated {len(MULTIPLIERS)} config pairs.")
    print("\nTo train each ablation:")
    for m in MULTIPLIERS:
        tag = mult_tag(m)
        print(f"  uv run train --config config/config_cm_mult{tag}.yml")


if __name__ == "__main__":
    main()
